name: "Podcast Generator"
author: "Justin Graham"
description: "Generates a feed for a podcast from a YAML"
runs:
  using: "docker"
  image: "Dockerfile"
branding: 
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The commiters email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The commiter's name
    required: true
    default: ${{ github.actor }}